# Generated by Django 3.1.2 on 2020-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=100)),
                ('leftFile', models.FileField(upload_to='')),
                ('rightFile', models.FileField(upload_to='')),
            ],
        ),
    ]
